version: "2"

services:
  icecast:
    image: infiniteproject/icecast
    volumes:
      - ./logs/icecast2:/var/log/icecast2
    environment:
      ICECAST_ADMIN_USERNAME: admin
      ICECAST_ADMIN_EMAIL: admin@example.com
      ICECAST_ADMIN_PASSWORD: hackme
      ICECAST_SOURCE_PASSWORD: hackme
      ICECAST_RELAY_PASSWORD: hackme
      ICECAST_LOCATION: Earth
      ICECAST_HOSTNAME: localhost
      ICECAST_MAX_CLIENTS:
    ports:
      - 8000:8000
  liquidsoap:
    image: infiniteproject/liquidsoap
    volumes:
      - ./logs/liquidsoap:/var/log
      - ./radio.liq:/var/radio.liq
      - ./playlists:/var/playlists
      - ./singles:/var/singles
      - ./music:/var/music
    links:
      - icecast
    entrypoint: /entrypoint.sh /var/radio.liq
